create table customers (
                           id bigint generated by default as identity primary key,
                           name varchar(100) not null,
                           surname varchar(100) not null,
                           tckn varchar(20) not null unique,
                           username varchar(100) not null unique,
                           password_hash varchar(255) not null,
                           role varchar(30) not null
);

create table wallets (
                         id bigint generated by default as identity primary key,
                         customer_id bigint not null,
                         wallet_name varchar(120) not null,
                         currency varchar(3) not null check (currency in ('TRY','USD','EUR')),
                         active_for_shopping boolean not null default false,
                         active_for_withdraw boolean not null default false,
                         balance numeric(19,2) not null default 0,
                         usable_balance numeric(19,2) not null default 0,
                         version int not null default 0,
                         constraint fk_wallet_customer foreign key (customer_id) references customers(id)
);

create table transactions (
                              id bigint generated by default as identity primary key,
                              wallet_id bigint not null,
                              amount numeric(19,2) not null check (amount > 0),
                              type varchar(10) not null check (type in ('DEPOSIT','WITHDRAW')),
                              opposite_party_type varchar(10) not null check (opposite_party_type in ('IBAN','PAYMENT')),
                              opposite_party varchar(64) not null,
                              status varchar(10) not null check (status in ('PENDING','APPROVED','DENIED')),
                              created_at timestamp not null default current_timestamp,
                              constraint fk_tx_wallet foreign key (wallet_id) references wallets(id)
);


create table idempotent_requests (
                                     id bigint generated by default as identity primary key,
                                     idempotency_key varchar(64) not null,
                                     endpoint varchar(120) not null,
                                     created_at timestamp not null default current_timestamp,
                                     unique(idempotency_key, endpoint)
);

create index idx_tx_wallet on transactions(wallet_id);
